### ISSUE TITLE
No folder `lib` in @solid/oidc-rp; PoPToken require in `SolidClient.js` should point to `src`

### ISSUE THREAD

**Issue by CxRes** [solid/solid-cli#14]
Like the title says! Is it sensible to point to a specific file inside another package (even if they might be owned by the same developers)? It seems like really brittle design! At the very least then `PoPToken.js` should be whitelisted in files in @solid/oidc-rp.

If this is desirable (or to be addressed at a later date), I can PR the change!

**Comment by RubenVerborgh** [comment]
#12 broke this, because 0.9.0 => 0.10.0 was a breaking change.

**Comment by RubenVerborgh** [comment]
> It seems like really brittle design!

It is… hence the giant warning at https://github.com/solid/solid-cli/blob/8aaf55e76c2ee4712c47230726f66577fc4b0535/README.md 🙂
We are phasing out our dependency on these packages.

**Comment by CxRes** [comment]
@RubenVerborgh Thanks!

The thing is, if we want to play around with Solid at this early stage, it does not leave one with much of a choice! I hope you guys are able to make speedy progress...
